/** 判断菜单栏选择情况 */
const SET_SHOW_HEADER = 'SET_SHOW_HEADER';
const FETCH_LOADING = 'FETCH_LOADING';
const SET_CURRENT_PAGE_TITLE = 'SET_CURRENT_PAGE_TITLE';

const SET_USER_INFO = 'SET_USER_INFO';
const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
const SET_TOKEN = 'SET_TOKEN';

const SET_NETWORK_ERROR = 'SET_NETWORK_ERROR';

// 车辆品牌 车系 车型选择常量
const SET_CAR_BRAND = 'SET_CAR_BRAND';
const SET_CAR_SERIES = 'SET_CAR_SERIES';
const SET_CAR_TYPE = 'SET_CAR_TYPE';

export default {
  SET_LOGIN_STATUS,
  SET_USER_INFO,
  SET_SHOW_HEADER,
  FETCH_LOADING,
  SET_CURRENT_PAGE_TITLE,
  SET_CAR_BRAND,
  SET_CAR_SERIES,
  SET_CAR_TYPE,
  SET_TOKEN,
  SET_NETWORK_ERROR,
};
